### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by arlind-ukshini** [Quka/TextAdventure#1]
## Thomas

- [x] Highscore (Navne på score)
- [ ] Kamp mod boss

### Monster
- [x] Monster skal have description
- [x] Skal skrives
- [x] Skal vises
- [x] Rum item fordeling

## Arlind

- [x] Man får item navn og beskrivelse når man modtager item
- [x] Når man pickup
- [ ] Når man modtager fra monster

## Mangler

- [x]  U - use item
- [ ] Lav "exit" item
- [x] Ret game class til
